# Generated by Django 4.0.6 on 2022-07-12 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0004_contact_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
