# Generated by Django 4.0.6 on 2022-07-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0006_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact1',
        ),
    ]
