# Generated by Django 4.0.6 on 2022-07-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0008_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact1',
        ),
    ]
