# Generated by Django 4.0.6 on 2022-07-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0011_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
