# Generated by Django 4.0.6 on 2022-07-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0013_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Contact',
        ),
    ]
