# Generated by Django 4.0.6 on 2022-07-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0015_rename_subject_contact_message_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='PRDImage',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='صور المنتج'),
        ),
    ]
