# Generated by Django 4.0.6 on 2022-07-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0016_alter_post_prdimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='lname',
            field=models.CharField(max_length=158, null=True),
        ),
    ]
